### ISSUE TITLE
No common ancestor

### ISSUE THREAD

**Issue by map82top** [Eliav2/react-xarrows#20]
Hello, tell me why this problem may occur?

![image](https://user-images.githubusercontent.com/36793054/83152707-ca0dd000-a106-11ea-96d5-892af888764f.png)

**Comment by map82top** [comment]
I have massive of arrows (start and end ids) in local component storage  . When I dropping first element and creating first arrow its work. But after dropping second element and creating second arrow throwed this exception.

**Comment by cole-robertson** [comment]
It looks like in file: https://github.com/Eliav2/react-xarrows/blob/master/src/index.tsx

There is code:
```ts
function commonAncestor(node1: any, node2: any) {
    var parents1 = parents(node1);
    var parents2 = parents(node2);

    // if (parents1[0] !== parents2[0]) throw new Error("No common ancestor!");
    if (parents1[0] !== parents2[0]) throw new Error("No common ancestor!");

    for (var i = 0; i < parents1.length; i++) {
      if (parents1[i] !== parents2[i]) return parents1[i - 1];
    }
  }
  return commonAncestor(elem, elem2);
};
```

It looks like, (as the error implies) that the parent of your two nodes is not the same. Docs state: `place the Xarrow under the relevent ancestor(of 'start' and 'end' element)`. Hopefully that helps, otherwise it might be good to share the component structure of your code.

**Comment by Eliav2** [comment]
Hey @map82top this CA be caused because either not valid id or ref passed to either start prop or end prop,
or it be caused if you tried to render the arrows earlier in the Dom tree before the components the arrow is attached to is placed in the Dom.(simple answer: make sure xarrow component is rendered later then his connected elements).

**Comment by Eliav2** [comment]
you do not respond - so I see this issue as close.
