### ISSUE TITLE
Arrows scale incorrectly after zoom change and element is dragged

### ISSUE THREAD

**Issue by PhucNgo1711** [Eliav2/react-xarrows#30]
Hello,

First of all this library is great! Saves me a lot of troubles! It also works great with the draggable library.
Now I'm trying to use it with a React pan zoom [library](https://github.com/prc5/react-zoom-pan-pinch). 
Everything looks good when you first zoom in/out and don't drag any element. However, when an element is dragged after the window zoom has changed, the arrows don't re-render correctly anymore. 
Here is a small sandbox I updated from your Example2. You can use the scrollwheel to zoom in/out, then try to drag one of the boxes. The arrow is hooked to the original scale.
https://codesandbox.io/s/zoomtest-7tug1

**Comment by Eliav2** [comment]
Hey!
first of all great demo!
I think I have a clue what causing this issue. I'm on it.

**Comment by PhucNgo1711** [comment]
Thanks!

**Comment by Eliav2** [comment]
I looked deeply in your case, it seems that 'react-zoom-pan-pinch' is scaling everything, but the arrow calculates the path after the scaling, and then the TransformWrapper component scale the arrow even though the path that was calculated taking into account that scale.
what you can do is to take xarrow outside TransformWrapper and rerender parent component when pinch and zoom.
see:
https://codesandbox.io/s/zoomtest-forked-piehd?file=/src/examplesFiles/Example2.jsx

**Comment by PhucNgo1711** [comment]
Wow thank you so much! This issue can be closed.

**Comment by farukparhat** [comment]
I just want to say cudos to @Eliav2 for the code sandbox because it unblocked me.
I was using react-zoom-pan-pinch and it totally fixed the issue if I moved the arrows outside of the wrappers for the zoom library.

For anyone else here, I also added the following style:
```
      <Xarrow
        start={start}
        end={end}
        strokeWidth={3 * currentZoomScale}
      />
```

Where currentZoomScale is the value returned by Zoom Pinch Pan's scale state. This way, if you zoom out the arrows do not enlarge but maintain the correct relative size despite being outside of the pinch zoom wrapper
